# ~/.cloudflared/config.yml
# 本机 Cloudflare Tunnel 配置文件

# 替换为你使用 `cloudflared tunnel create k-app` 时生成的 TUNNEL_ID
tunnel: fa7926f0-878e-400e-83b7-7ccf27ef5f01
credentials-file: /root/.cloudflared/fa7926f0-878e-400e-83b7-7ccf27ef5f01.json

ingress:
  # 替换为你的后端 API 域名
  - hostname: api.ppro8monitor.com
    # 你的 server.js 运行在 3000 端口
    service: http://localhost:3000
  - service: http_status:404
